spring:
  application:
    name: gateway-service          # Eureka-ya bu adla register olacaq
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthenticationFilter
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/card/**,/readList/**
          filters:
            - AuthenticationFilter # Request service getmezden qabaq filtere dusecek
        - id: payment-service
          uri: lb://payment-service # For load balanncing
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**,/api/v1/order/**
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            exposedHeaders: "*"

server:
  port: 8888

# Eurekaya baglayiriq(eurekanin url-ini veririk?)
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true